######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 20 00:14:58 2013
######################################################################

QT -= gui
CONFIG += console debug
TEMPLATE = app
TARGET = 
DEPENDPATH += . old
INCLUDEPATH += .

# Input
HEADERS += huffman.h
SOURCES += huffman.cpp main.cpp
